# Checkstyle-IDEA plugin configuration

# TODO: This should probably contain every version that is supported from the recently removed checkstyle.versions.map
#  property. Meaning, 8.0, 8.1, 8.2, etc. should be in this list instead of just 9.0.1.
checkstyle.versions.supported = \
    9.0.1, 9.1, 9.2.1, 9.3, \
    10.0, 10.1, 10.2, 10.3.4, 10.4, 10.5.0, 10.6.0, 10.7.0, 10.8.1, 10.9.3, \
    10.10.0, 10.12.7, 10.13.0, 10.14.2, 10.15.0, 10.16.0, 10.17.0, 10.18.2, 10.19.0, \
    10.20.2, 10.21.3, 10.22.0, 10.23.0, 10.24.0, 10.25.1, 10.26.1

# The "base version" must be one of the versions listed above. The sources are compiled against this version, so it is
# the dependency shown in the IDE and the runtime used when unit tests are run from the IDE or via 'runCsaccessTests'.
baseVersion = 9.0.1
